apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: ghcr.io/alexriley7/streaming-system/producer:a00d160a822d87a66b591c659c02940b38bd9ec4
          imagePullPolicy: Always

          # Added:

          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092

            - name: ENABLE_PRODUCER
              value: "false"   # switch to "false" to stop producing

            - name: TOPIC
              value: input-topic


      imagePullSecrets:
        - name: ghcr-secret