apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: ghcr.io/alexriley7/streaming-system/producer:05d0ba33cb2b424ae0a5510d0c3fa8bac366a0b1
          imagePullPolicy: Always

          # Added: 

          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092

            - name: ENABLE_PRODUCER
              value: "true"   # switch to "false" to stop producing

            - name: TOPIC
              value: input-topic-debug-a2


      imagePullSecrets:
        - name: ghcr-secret