apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-transformation-v1
  namespace: flink
spec:
  image: ghcr.io/alexriley7/streaming-system/flink-transformation:7522b61192d62f9f717df48997d8f8d2ddacc775
  flinkVersion: v1_18
  serviceAccount: flink-sa

  jobManager:
    resource:
      cpu: 0.25
      memory: "1024m"

  taskManager:
    resource:
      cpu: 0.25
      memory: "1024m"

  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"

  job:
    jarURI: local:///opt/flink/usrlib/job.jar
    entryClass: com.example.FlinkTransformationJob   # 👈 ADD THIS
    parallelism: 1
    upgradeMode: stateless
    state: running

  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092

            - name: GROUP_ID
              value: flink-consumer-v1

            - name: ENABLE_JOB
              value: "true"   # switch to "false" to stop producing

            - name: OUTPUT_TOPIC
              value: "output-topic-v1"