apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-transformation-v1
  namespace: flink
spec:
  image: ghcr.io/alexriley7/streaming-system/flink-transformation:82c581143ce2de8ec2f4ce78c6c610823b4a2bdc
  flinkVersion: v1_18
  serviceAccount: flink-sa

  jobManager:
    resource:
      cpu: 0.5
      memory: "1024"

  taskManager:
    resource:
      cpu: 0.5
      memory: "1024"

  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "3"

  job:
    jarURI: local:///opt/flink/usrlib/job.jar
    entryClass: com.example.FlinkTransformationJob   # 👈 ADD THIS
    parallelism: 3
    upgradeMode: stateless
    state: running

  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092

            - name: GROUP_ID
              value: flink-consumer-v1