apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-app
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/alexriley7/streaming-system-deploy.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true