apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: ghcr.io/alexriley7/streaming-system/consumer:278c3e64009498c8c259351007d6f8f8e97bed34
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: 172.17.0.1:9092
            - name: GROUP_ID
              value: "consumer-group-1"
      imagePullSecrets:
        - name: ghcr-secret
        