apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment

metadata:
  name: shadow-flink-transformation-v2
  namespace: flink

spec:

  image: ghcr.io/alexriley7/streaming-system/shadow-flink-transformation:7be8a042ec708ae6c123fd0349e734895cf436e4

  flinkVersion: v1_18

  serviceAccount: flink-sa



  # ==========================================================
  # JOB MANAGER
  # ==========================================================

  jobManager:
    resource:
      cpu: 0.25
      memory: "1024m"

  # ==========================================================
  # TASK MANAGER
  # ==========================================================

  taskManager:
    resource:
      cpu: 0.25
      memory: "1024m"

  # ==========================================================
  # FLINK CONFIGURATION
  # ==========================================================

  flinkConfiguration:

    taskmanager.numberOfTaskSlots: "1"

    # --------------------------------------------------------
    # STATE BACKEND
    # --------------------------------------------------------

    state.backend: hashmap

    # --------------------------------------------------------
    # CHECKPOINTS / SAVEPOINTS
    # --------------------------------------------------------

    execution.checkpointing.interval: "30s"

    state.checkpoints.dir: file:///data/flink-checkpoints/checkpoints-debug-v2x

    state.savepoints.dir: file:///data/flink-savepoints/savepoints-debug-v2x

    state.checkpoints.num-retained: "5"



    taskmanager.numberOfTaskSlots: "1"

    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory

    metrics.reporter.prom.port: "9249"

    # --------------------------------------------------------
    # S3 / MOTO
    # --------------------------------------------------------

    s3.endpoint: http://moto-s3.default.svc.cluster.local:5000

    s3.path.style.access: "true"

    s3.access-key: test

    s3.secret-key: test

    s3.connection.ssl.enabled: "false"

  # ==========================================================
  # FLINK JOB
  # ==========================================================

  job:

    jarURI: local:///opt/flink/usrlib/job.jar

    entryClass: com.example.ShadowFlinkTransformationJob

    parallelism: 1

    upgradeMode: stateless

    state: running

    savepointTriggerNonce: 2

  # ==========================================================
  # POD TEMPLATE
  # ==========================================================

  podTemplate:

    spec:


      securityContext:

        fsGroup: 9999

      containers:

        - name: flink-main-container

          env:

            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092

            - name: GROUP_ID
              value: shadow-flink-debug-b1-v1

            - name: ENABLE_JOB
              value: "true"

            - name: OUTPUT_TOPIC
              value: "shadow-output-topic-debug-b1"


          ports:

            - containerPort: 9249
              name: metrics

          # --------------------------------------------------
          # MOUNT CHECKPOINT STORAGE##
          # --------------------------------------------------

          volumeMounts:

            - name: shadow-flink-checkpoints-volume
              mountPath: /data/shadow-flink-checkpoints

      # ------------------------------------------------------
      # PVC VOLUME
      # ------------------------------------------------------

      volumes:

        - name: shadow-flink-checkpoints-volume

          persistentVolumeClaim:
            claimName: shadow-flink-checkpoints-pvc-debug