apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-profile
spec:
  replicas: 1 #switch to 0 to stop producer
  selector:
    matchLabels:
      app: producer-profile
  template:
    metadata:
      labels:
        app: producer-profile
    spec:
      containers:
        - name: profile-producer
          image: ghcr.io/alexriley7/streaming-system/producer-profile:f8fa75ea1c63e9ef1c6251e6dbecde3916ebbc3b
          imagePullPolicy: Always

          # Added: 

          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092

            - name: ENABLE_PRODUCER
              value: "true"   # switch to "false" to stop producing

            - name: TOPIC
              value: profiles-input-topic-debug-b1


      imagePullSecrets:
        - name: ghcr-secret